// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_WIN_API_KEY'].toString(),
    appId: dotenv.env['WEB_APP_ID'].toString(),
    messagingSenderId: dotenv.env['MESSENGER_ID'].toString(),
    projectId: dotenv.env['PROJECT_ID'].toString(),
    authDomain: dotenv.env['AUTH_DOMAIN'].toString(),
    storageBucket: dotenv.env['STORAGE_BUCKET'].toString(),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'].toString(),
    appId: dotenv.env['ANDROID_APP_ID'].toString(),
    messagingSenderId: dotenv.env['MESSENGER_ID'].toString(),
    projectId: dotenv.env['PROJECT_ID'].toString(),
    storageBucket: dotenv.env['STORAGE_BUCKET'].toString(),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_MAC_API_KEY'].toString(),
    appId: dotenv.env['IOS_MAC_APP_ID'].toString(),
    messagingSenderId: dotenv.env['MESSENGER_ID'].toString(),
    projectId: dotenv.env['PROJECT_ID'].toString(),
    storageBucket: dotenv.env['STORAGE_BUCKET'].toString(),
    iosBundleId: dotenv.env['IOS_MAC_BUNDLE_ID'].toString(),
  );
}
